# version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:3000"
    environment:
      - PORT=3000
      - FRONTEND_URL=http://localhost:3000
      - ATLAS_DB_URL=${ATLAS_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always